### ISSUE TITLE
Support for build with Docker container

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#1088]
I've found this post: https://docs.haskellstack.org/en/stable/docker_integration/
I think very promising for us.
Unfortunately no support for Windows yet.. but there's a fix coming very soon I gues: https://github.com/commercialhaskell/stack/issues/2421 and https://github.com/commercialhaskell/stack/pull/5315

Integration of stack with docker can be specified/configured in `stack.yaml`

```yaml
# Docker integration
# See: 
docker:
  enable: true
# Note that in a docker-enabled configuration, stack uses the GHC installed in the Docker container by default.
# We want to use the compiler installed by stack
system-ghc: false
```

Tbc
