### ISSUE TITLE
Cannot install front end framework when using Docker

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#810]
As an Ampersand user, I want to run my script using docker. I generated my own Ampersand image from github/AmpersandTarski/docker-ampersand/, by using the command `./build.sh`. Then I tried to compile `Hawaii.adl` by running `docker-compose up`.

#### Version of ampersand that was used 
I have used Ampersand-v3.11.0 [HEAD:d1ce3dd*]

#### What I expected
I expected a working demo of Hawaii, but got a compile time error instead.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/275768/42452324-fd262132-8389-11e8-8d7d-13efe33ba64a.png)

#### Context / Source of ampersand script
By issuing the command:
```
BA92-2VP224HTDF:Hawaii stefjoosten$ cat docker-compose.yml
```
I ensured having the correct docker-compose.yml file
```
version: '3'

services:
  prototype:
    restart: always
    build:
      context: .
      args:
        ADL_FILE: Hawaii.adl

    ports:
      - "80:80"
    links:
      - db
 
  db:
    restart: always
    image: ampersandtarski/ampersand-prototype-db

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
       - "8080:80"
    links:
      - db
```
I ran into this bug in an attempt to get demos of Ampersand with the new front-end framework to work on my MacBook.
